config/routes.rb
Rails.application.routes.draw do



  root :to => 'tops#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root 'tops#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}


  resources :users
  resources :tops
  resources :drinks
  resources :foods
  resources :side_menus
  resources :sakes

  resources :blogs do
    resources :comments
  end
  resources :maps, only: [:index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  validates :title, presence: true
  validates :title, length:{in:1..20}
  validates :content, presence: true
  validates :content, length:{in:1..50}
  validate :visitday_cannot_be_in_the_pastday
  validates :status, presence: true

  def visitday_cannot_be_in_the_pastday
    if visit_date.present? && visit_date < Date.today
      errors.add(:visit_date, "過去の日は入力できません。")
    end
  end


  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :picture, ImageUploader
  enum status:{緊急: 0,とても重要: 1,重要: 2,ふつう: 3, いつでもよい: 4}, _suffix: true



end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
  validates :content, presence: true
  validates :content, length:{in:1..100}

end

app/models/drink.rb
class Drink < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}
  validates :kind, presence: true
  enum kind:{ドリンク: 0,ウイスキー、ハイボール: 1,プレミアム焼酎ハイボール: 2,サワー、お茶ハイ: 3}, _suffix: true
end

app/models/food.rb
class Food < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}

end

app/models/sake.rb
class Sake < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, absence: true
  validates :kind, presence: true
  enum kind:{一列目: 0,二列目: 1,三列目: 2,四列目: 3}, _suffix: true
end

app/models/side_menu.rb
class SideMenu < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}
  validates :kind, presence: true
  enum kind:{一品料理: 0,〆もの: 1}, _suffix: true
end

app/models/top.rb
class Top < ApplicationRecord
  mount_uploader :picture, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true
  validates :email, uniqueness: true

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }




  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google]
  has_many :blogs
  has_many :comments, through: :blogs


  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    puts '**********'
    puts auth.info
    puts '**********'

    unless user
      user = User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                 )
    end
    user.save
    user
  end



  def self.find_for_facebook(auth)
    user = User.find_by(email: auth.info.email)
    puts '**********'
    puts auth.info
    puts '**********'

    unless user
      user = User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                 )
    end
    user.save
    user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]


  PER = 4

  def index
    @blogs = Blog.all.order("created_at DESC").page(params[:page]).per(PER)

    if params[:sort_created]
      @blogs = Blog.all.order("created_at DESC").page(params[:page]).per(PER)
    end

    if params[:sort_status]
      @blogs = Blog.all.order("status ASC").page(params[:page]).per(PER)
    end

    if params[:sort_visit_date]
      @blogs = Blog.all.order("visit_date ASC").page(params[:page]).per(PER)
    end
  end

  def new
    if current_user == nil
      redirect_to tops_path, notice:"権限がありません。"
    end
    @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blogs_path, notice:"業務連絡を作成しました。"
    else
      render :new
    end
  end

  def show
    @comments = @blog.comments

    @comment = @blog.comments.build
  end

  def edit


    if current_user.id == @blog.user.id || current_user.admin == true
    elsif current_user == nil
      redirect_to tops_path, notice:"権限がありません。"
    elsif current_user.id != @blog.user_id
      redirect_to tops_path, notice:"権限がありません。"

    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice:"業務連絡を編集しました。"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"業務連絡を削除しました。"
  end


  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :picture, :picture_cache, :priority, :visit_date, :status, :user_id )
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/oauth_test_helper.rb
module OauthTestHelper
end

app/helpers/sakes_helper.rb
module SakesHelper
end

app/helpers/side_menus_helper.rb
module SideMenusHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%=msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="blog_visit_date">
    <%= form.label :visit_date %>
    <%= form.date_select :visit_date,  include_blank: true %>
  </div>

  <div class="blog_status">
    <%= form.label :status %>
    <%= form.select :status, Blog.statuses.keys.to_a, {} %>

  </div>

  <div class="blog_picture">
    <%= form.label :picture %>
    <% if @blog.picture.url %>
      <%= image_tag @blog.picture.url ,:width => '400', :height => '400' %>
    <% end %>
    <br>
    <%= form.file_field :picture %>



  </div>

  <%= form.submit %>
<% end %>

app/views/blogs/edit.html.erb
<div class="blogeditbody">
<div class="blogeachtitle">
<p1>業務連絡を編集画面</p1>
</div>
<br>
<br>
<button type="button" class="btn btn-success rounded-pill">
<%= link_to "業務連絡一覧へ戻る", blogs_path %></button>

<br>
<br>

<%= render 'form' %>

</div>

app/views/blogs/index.html.erb
<div class="blog">
  <div class='blogtitle'>
<p1>業務連絡一覧画面</p1>
  </div>

<button type="button" class="btn btn-primary rounded-0">
<%= link_to '優先度でソートする', blogs_path(sort_status: "true") %></button>

<button type="button" class="btn btn-primary rounded-0">
<%= link_to '完了予定期日でソートする', blogs_path(sort_visit_date: "true") %></button>

<button type="button" class="btn btn-primary rounded-0">
<%= link_to '最新順でソートする', blogs_path(sort_created: "true") %></button>

<% if user_signed_in? %>
<button type="button" class="btn btn-danger rounded-pill">
  <%=link_to '業務連絡を登録する', new_blog_path %></button>
<% end %>

<% if current_user == nil %>
<% elsif current_user.admin %>
<button type="button" class="btn btn-success rounded-pill">
  <%= link_to '従業員一覧へ', users_path %></button>
<% end %>

<button type="button" class="btn btn-secondary rounded-0">
<%= paginate @blogs %></button>

<br>

<table class="table table-hover">
  <tr>
    <th>従業員名</th>
    <th>タイトル</th>
    <th>写真</th>
    <th>作成日</th>
    <th>優先度</th>
    <th>完了予定期日</th>
    <th colspan="3"></th>


  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.user.name %></td>

    <td><%= blog.title %></td>
    <td><% if blog.picture.url %>
      <%=  '🐓'%>
        <% else %>
      <%=   'なし'%>
        <% end %>
    </td>
    <td><%= blog.created_at.strftime('%Y年%m月%d日')%></td>



    <td><%= blog.status %></td>

    <td><% if blog.visit_date %>
      <%= blog.visit_date.strftime('%Y年%m月%d日') %>
        <% else %>
      <%= blog.visit_date %>
        <% end %>
    </td>



    <td>
      <button type="button" class="btn btn-info rounded-pill"><%= link_to '詳細', blog_path(blog.id) %></button></td>

    <% if current_user == nil %>
    <% elsif current_user.id == blog.user_id || current_user.admin %>
      <td><button type="button" class="btn btn-warning rounded-pill">
        <%= link_to '編集', edit_blog_path(blog.id) %></button></td>
      <td><button type="button" class="btn btn-secondary rounded-pill">
        <%= link_to '削除', blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></button></td>
    <% end %>


  </tr>
<% end %>
</table>
</div>

app/views/blogs/new.html.erb
<div class="blognewbody">
<div class="blogeachtitle">
<p1> 業務連絡作成画面</p1>
</div>
<br>
<br>
<button type="button" class="btn btn-success rounded-pill">
<%= link_to "業務連絡一覧へ戻る", blogs_path %></button>

<br>
<br>

<%= render 'form' %>

</div>

app/views/blogs/show.html.erb
<div class="blogshowbody">
  <div class="blogeachtitle">
　<p1>詳細画面</p1>
  </div>
  <br>
  <button type="button" class="btn btn-success rounded-pill">
  <%= link_to '業務連絡一覧へ戻る', blogs_path %></button>


  <div class="blog-text">
    <table>
    <p><strong>タイトル</strong>：<%= @blog.title %></p>
    <p><strong>内容</strong>：<%= @blog.content %></p>

    <p><strong>写真</strong>：
      <% if  @blog.picture.url %>
      <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter-<%= @blog.id %>">
      <%=  '🐓' %>
    <% else %>
      <%= '写真はありません'%>
    <% end %>
      </button>
    <div class="modal fade" id="exampleModalCenter-<%= @blog.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle-<%= @blog.id %>" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
              </button>
          </div>
            <div class="modal-body">
              <div class="modalpicture">
                <p>
                  <% if  @blog.picture.url %>
                  <%= image_tag @blog.picture.url ,:width => '400', :height => '400'  %></p>
                  <% elsif @blog.picture.url == nil %>
                  <% end %>
              </div>
            </div>
          <div class="modal-footer">
          </div>
        </div>
      </div>
    </div>

    <table class="table table-hover">
      <tr>
        <th>完了予定日</th>
        <th>優先度</th>

      </tr>
      <tr>
        <td><%= @blog.visit_date %></td>
        <td><%= @blog.status %></td>

      </tr>
    </table>
  </div>
  <div class="jumbotron jumbotron-fluid">
  <p1 class="comment_board">コメント一覧</p1>
  <br>
  <br>

   
  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
  </div>
  <% if current_user == nil %>
  <% elsif current_user %>
  <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
  <% end %>

  </div>


</div>