config/routes.rb
Rails.application.routes.draw do



  root :to => 'tops#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root 'tops#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}


  resources :users
  resources :tops
  resources :drinks
  resources :foods
  resources :side_menus
  resources :sakes

  resources :blogs do
    resources :comments
  end
  resources :maps, only: [:index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  validates :title, presence: true
  validates :title, length:{in:1..20}
  validates :content, presence: true
  validates :content, length:{in:1..50}
  validate :visitday_cannot_be_in_the_pastday
  validates :status, presence: true

  def visitday_cannot_be_in_the_pastday
    if visit_date.present? && visit_date < Date.today
      errors.add(:visit_date, "過去の日は入力できません。")
    end
  end


  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :picture, ImageUploader
  enum status:{緊急: 0,とても重要: 1,重要: 2,ふつう: 3, いつでもよい: 4}, _suffix: true



end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
  validates :content, presence: true
  validates :content, length:{in:1..100}

end

app/models/drink.rb
class Drink < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}
  validates :kind, presence: true
  enum kind:{ドリンク: 0,ウイスキー、ハイボール: 1,プレミアム焼酎ハイボール: 2,サワー、お茶ハイ: 3}, _suffix: true
end

app/models/food.rb
class Food < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}

end

app/models/sake.rb
class Sake < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, absence: true
  validates :kind, presence: true
  enum kind:{一列目: 0,二列目: 1,三列目: 2,四列目: 3}, _suffix: true
end

app/models/side_menu.rb
class SideMenu < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}
  validates :kind, presence: true
  enum kind:{一品料理: 0,〆もの: 1}, _suffix: true
end

app/models/top.rb
class Top < ApplicationRecord
  mount_uploader :picture, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true
  validates :email, uniqueness: true

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }




  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google]
  has_many :blogs
  has_many :comments, through: :blogs


  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    puts '**********'
    puts auth.info
    puts '**********'

    unless user
      user = User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                 )
    end
    user.save
    user
  end



  def self.find_for_facebook(auth)
    user = User.find_by(email: auth.info.email)
    puts '**********'
    puts auth.info
    puts '**********'

    unless user
      user = User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                 )
    end
    user.save
    user
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/sakes_controller.rb
class SakesController < ApplicationController
  before_action :set_sake, only: [:show, :edit, :update, :destroy]
  before_action :refuse_to_go_to, only: [:new, :edit]

  def index
    @sakes = Sake.all
  end

  def new
      @sake = Sake.new
  end

  def create
    @sake = Sake.create(sake_params)
    if @sake.save
      redirect_to sakes_path, notice:"日本酒を作成しました！"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @sake.update(sake_params)
      redirect_to sakes_path, notice:"日本酒を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @sake.destroy
    redirect_to sakes_path, notice:"日本酒を削除しました！"
  end

  private

  def sake_params
    params.require(:sake).permit(:name, :picture, :picture_cache, :price, :comment, :kind)
  end

  def set_sake
    @sake = Sake.find(params[:id])
  end

  def refuse_to_go_to
    if current_user == nil
      redirect_to tops_path, notice: '権限がありません。'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/oauth_test_helper.rb
module OauthTestHelper
end

app/helpers/sakes_helper.rb
module SakesHelper
end

app/helpers/side_menus_helper.rb
module SideMenusHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sakes/_form.html.erb

<%= form_with(model: @sake, local: true) do |form| %>
  <% if @sake.errors.any? %>
    <div id="error_explanation">
      <h2><%= @sake.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @sake.errors.full_messages.each do |msg| %>
        <li><%=msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="sake_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="sake_picture">
    <%= form.label :picture%>
    <%= form.file_field :picture %>
    <% if @sake.picture.url %>
      <%= image_tag @sake.picture.url, :width => '25%', :height => '25%'  %>
    <% end %>
    <br>

  </div>
  <div class="sake_price">
    <%= form.label :price %>
    <%= form.number_field(:price, in: 1..99999, step: 1.0) %>
  </div>

  <div class="sake_kind">
    <%= form.label :kind %>
    <%= form.select :kind, Sake.kinds.keys.to_a, {} %>
  </div>


  <%= form.submit %>
<% end %>

<%= link_to "日本酒一覧画面に戻る", sakes_path %>

app/views/sakes/edit.html.erb
<div class="menuediter">
<h2>日本酒を編集する</h2>
<%= render 'form' %>
</div>

app/views/sakes/index.html.erb
<div class = "sakebody">
<div class ="container">
  <div class="ordertype">
    <p1>日本酒</p1>
  </div>
  <div class="order-title" >
      <p2>店主がこだわりの日本酒を季節に合わせ厳選したものを仕入れており、
      純米酒、純米吟醸、純米大吟醸、熟清酒など幅広くご提供させて頂いております。
      ワイングラスで600円～800円よりご提供させて頂いております。</p2>
  </div>
  <% if current_user == nil %>
  <% elsif %>
    <button type="button" class="btn btn-danger rounded-pill">
    <%= link_to '新しく日本酒を登録する', new_sake_path %></button>
  <% end %>

  <br>



  <div class="row">

    <div class="col">
      <div sakekind0>
        <table>
          <thead>
            <tr>
              <th height="30"></th>
              <th height="30"></th>

            </tr>
          </thead>
          <tbody>
            <% @sakes.each do |sake| %>
            <% if sake.kind == '一列目' %>
            <tr>
              <td width=300><%= sake.name %></td>
              <td><%= sake.price %></td>
              <td>
                <% if sake.picture && sake.picture.url %>
                  <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter-<%= sake.id %>">
                  <%=  '🐓' %>
                <% else %>
                  <%= '　'%>
                <% end %>
                  </button>
                  <div class="modal fade" id="exampleModalCenter-<%= sake.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle-<%= sake.id %>" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <p5 class="modal-title" id="exampleModalCenterTitle-<%= sake.id %>"><%= sake.name %></p5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                          <div class="modal-body">
                            <div class="modalpicture">
                              <p><%= image_tag "#{sake.picture.url}",:width => '50%', :height => '50%' %></p>
                            </div>
                          </div>
                        <div class="modal-footer">
                        </div>
                      </div>
                    </div>
                  </div>
               </td>

              <% if current_user == nil %>
              <% elsif %>
              <td>
                <button type="button" class="btn btn-warning rounded-pill">
                <%= link_to "編集", edit_sake_path(sake.id), data: { confirm: '本当に編集していいですか？' } %></button></td>
              <td>
                <button type="button" class="btn btn-secondary rounded-pill">
                <%= link_to '削除', sake_path(sake.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></button></td>
              <% end %>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col">
      <div sakekind1>
        <table>
          <thead>
            <tr>
              <th height="30"></th>
              <th height="30"></th> 

            </tr>
          </thead>
          <tbody>
            <% @sakes.each do |sake| %>
            <% if sake.kind == '二列目' %>
            <tr>
              <td width=300><%= sake.name %></td>
              <td><%= sake.price %></td>
              <td>
                <% if sake.picture && sake.picture.url %>
                  <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter-<%= sake.id %>">
                  <%=  '🐓' %>
                <% else %>
                  <%= '　'%>
                <% end %>
                  </button>
                  <div class="modal fade" id="exampleModalCenter-<%= sake.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle-<%= sake.id %>" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <p5 class="modal-title" id="exampleModalCenterTitle-<%= sake.id %>"><%= sake.name %></p5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                          <div class="modal-body">
                            <div class="modalpicture">
                              <p><%= image_tag "#{sake.picture.url}",:width => '50%', :height => '50%' %></p>
                            </div>
                          </div>
                        <div class="modal-footer">
                        </div>
                      </div>
                    </div>
                  </div>
               </td>

              <% if current_user == nil %>
              <% elsif %>
              <td>
                <button type="button" class="btn btn-warning rounded-pill">
                <%= link_to "編集", edit_sake_path(sake.id), data: { confirm: '本当に編集していいですか？' } %></button></td>
              <td>
                <button type="button" class="btn btn-secondary rounded-pill">
                <%= link_to '削除', sake_path(sake.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></button></td>
              <% end %>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>



<div class="w-100"></div>





    <div class="col">
      <div sakekind2>
        <table>
          <thead>
           <tr>
             <th></th>
             <th></th>
           </tr>
          </thead>
        <tbody>
          <% @sakes.each do |sake| %>
            <% if sake.kind == '三列目' %>
          <tr>
           <td width=300 ><%= sake.name %></td>
           <td>
             <% if sake.picture && sake.picture.url %>
               <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter-<%= sake.id %>">
               <%=  '🐓' %>
             <% else %>
               <%= '　'%>
             <% end %>
               </button>
               <div class="modal fade" id="exampleModalCenter-<%= sake.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle-<%= sake.id %>" aria-hidden="true">
                 <div class="modal-dialog modal-dialog-centered" role="document">
                   <div class="modal-content">
                     <div class="modal-header">
                       <p5 class="modal-title" id="exampleModalCenterTitle-<%= sake.id %>"><%= sake.name %></p5>
                         <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                           <span aria-hidden="true">&times;</span>
                         </button>
                     </div>
                       <div class="modal-body">
                         <div class="modalpicture">
                           <p><%= image_tag "#{sake.picture.url}",:width => '50%', :height => '50%' %></p>
                         </div>
                       </div>
                     <div class="modal-footer">
                     </div>
                   </div>
                 </div>
               </div>
            </td>

           <td><%= sake.price %></td>
              <% if current_user == nil %>
              <% elsif %>
                <td>
                  <button type="button" class="btn btn-warning rounded-pill">
                  <%= link_to "編集", edit_sake_path(sake.id), data: { confirm: '本当に編集していいですか？' } %></button></td>
                <td>
                  <button type="button" class="btn btn-secondary rounded-pill">
                  <%= link_to '削除', sake_path(sake.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></button></td>
              <% end %>
          </tr>　
            <% end %>
          <% end %>
        </tbody>
        </table>
      </div>
    </div>



    <div class="col">
     <div sakekind3>
       <table>
         <thead>
          <tr>　
            <th></th>
            <th></th>
          </tr>
         </thead>
       <tbody>
         <% @sakes.each do |sake| %>
           <% if sake.kind == '四列目' %>
         <tr>
          <td width=300><%= sake.name %></td>
          <td>
            <% if sake.picture && sake.picture.url %>
              <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter-<%= sake.id %>">
              <%=  '🐓' %>
            <% else %>
              <%= '　'%>
            <% end %>
              </button>
              <div class="modal fade" id="exampleModalCenter-<%= sake.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle-<%= sake.id %>" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <p5 class="modal-title" id="exampleModalCenterTitle-<%= sake.id %>"><%= sake.name %></p5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                          <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                      <div class="modal-body">
                        <div class="modalpicture">
                          <p><%= image_tag "#{sake.picture.url}",:width => '50%', :height => '50%' %></p>
                        </div>
                      </div>
                    <div class="modal-footer">
                    </div>
                  </div>
                </div>
              </div>
           </td>

          <td><%= sake.price %></td>
             <% if current_user == nil %>
             <% elsif %>
               <td>
                 <button type="button" class="btn btn-warning rounded-pill">
                 <%= link_to "編集", edit_sake_path(sake.id), data: { confirm: '本当に編集していいですか？' } %></button></td>
               <td>
                 <button type="button" class="btn btn-secondary rounded-pill">
                 <%= link_to '削除', sake_path(sake.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></button></td>
             <% end %>
         </tr>
           <% end %>
         <% end %>
       </tbody>
       </table>
     </div>
    </div>

    <br>



<br>

</div>
</div>

app/views/sakes/new.html.erb
<div class="menuediter">
<h2>日本酒を作成する</h2>
<%= render 'form' %>
</div>

app/views/sakes/show.html.erb
<h1>日本酒詳細画面</h1>
<p>日本酒: <%= @sake.name %></p>
<p>
  <strong>写真: </strong>
  <%= image_tag @sake.picture.url %>
</p>
<p>値段: <%= @sake.price %></p>

<%= link_to "日本酒一覧画面に戻る", sakes_path %>