config/routes.rb
Rails.application.routes.draw do



  root :to => 'tops#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root 'tops#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}


  resources :users
  resources :tops
  resources :drinks
  resources :foods
  resources :side_menus
  resources :sakes

  resources :blogs do
    resources :comments
  end
  resources :maps, only: [:index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  validates :title, presence: true
  validates :title, length:{in:1..20}
  validates :content, presence: true
  validates :content, length:{in:1..50}
  validate :visitday_cannot_be_in_the_pastday
  validates :status, presence: true

  def visitday_cannot_be_in_the_pastday
    if visit_date.present? && visit_date < Date.today
      errors.add(:visit_date, "過去の日は入力できません。")
    end
  end


  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :picture, ImageUploader
  enum status:{緊急: 0,とても重要: 1,重要: 2,ふつう: 3, いつでもよい: 4}, _suffix: true



end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
  validates :content, presence: true
  validates :content, length:{in:1..100}

end

app/models/drink.rb
class Drink < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}
  validates :kind, presence: true
  enum kind:{ドリンク: 0,ウイスキー、ハイボール: 1,プレミアム焼酎ハイボール: 2,サワー、お茶ハイ: 3}, _suffix: true
end

app/models/food.rb
class Food < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}

end

app/models/sake.rb
class Sake < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, absence: true
  validates :kind, presence: true
  enum kind:{一列目: 0,二列目: 1,三列目: 2,四列目: 3}, _suffix: true
end

app/models/side_menu.rb
class SideMenu < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}
  validates :kind, presence: true
  enum kind:{一品料理: 0,〆もの: 1}, _suffix: true
end

app/models/top.rb
class Top < ApplicationRecord
  mount_uploader :picture, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true
  validates :email, uniqueness: true

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }




  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google]
  has_many :blogs
  has_many :comments, through: :blogs


  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    puts '**********'
    puts auth.info
    puts '**********'

    unless user
      user = User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                 )
    end
    user.save
    user
  end



  def self.find_for_facebook(auth)
    user = User.find_by(email: auth.info.email)
    puts '**********'
    puts auth.info
    puts '**********'

    unless user
      user = User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                 )
    end
    user.save
    user
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/oauth_test_helper.rb
module OauthTestHelper
end

app/helpers/sakes_helper.rb
module SakesHelper
end

app/helpers/side_menus_helper.rb
module SideMenusHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tops/index.html.erb
<div class="toppbody">
<div class="f-container">


<p1>
江戸川区瑞江の外れにひっそりと店を構える
炭火焼き鳥店</p1>
<br>
<p2>
当店で召し上がって頂きたいのは、<br>
40種類以上の希少部位の中から日替わりで提供する部位を備長炭で丁寧に焼き上げた焼き鳥です。<br>
鳥を1からさばき、質の良い部位を鮮度の良い状態で丁寧に仕込み、提供しております。<br>
極上の塩、秘伝のタレで是非お召し上がりください。<br>
また、焼き鳥に合う店主が厳選した日本酒を多数取り揃えておりますので『焼き鳥×日本酒』をご堪能くださいませ。</p2>
<br>
<br>
<p1>お店のインスタグラムはこちらから</p1>
 <button type="button" class="btn btn-info rounded-pill">
  <%= link_to "Instagram", "https://www.instagram.com/toriyuu_yakitori", :target=>["_blank"] %></button>
<br>
<br>
<p1>当店では団体様用のお座敷席もご用意しております。</p1>


<button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModalCenter">
  <p1>お座敷席</p1>
</button>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered modal-xl" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <p5 class="modal-title" id="exampleModalCenterTitle">お座敷席</p5>
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
      <div class="modal-body">
        <div class="modalpicture">
          <p><%= image_tag "14372.jpg",:width => '100%', :height => '100%'  %></p>
        </div>
      </div>
    <!-- <div class="modal-footer">
    </div> -->
  </div>
</div>
</div>

<br>
<br>
<p1>以下より各リンクにいけます。</p1>
<div class="top-sub">
        <button type="button" class="btn btn-light rounded-pill">
            <%= link_to "トップページ", tops_path %></button>
       <button type="button" class="btn btn-light rounded-pill">
            <%= link_to "アクセス", maps_path %></button>
        <br>
          <button type="button" class="btn btn-warning rounded-pill">
            <%= link_to "焼き鳥", foods_path %></button>
          <button type="button" class="btn btn-warning rounded-pill">
            <%= link_to "一品料理", side_menus_path %></button>
          <button type="button" class="btn btn-warning rounded-pill">
            <%= link_to "お飲み物", drinks_path %></button>
          <button type="button" class="btn btn-warning rounded-pill">
            <%= link_to "日本酒", sakes_path %></button>
        <br>
        </div>
      </div>









</div>
</div>