config/routes.rb
Rails.application.routes.draw do



  root :to => 'tops#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root 'tops#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}


  resources :users
  resources :tops
  resources :drinks
  resources :foods
  resources :side_menus
  resources :sakes

  resources :blogs do
    resources :comments
  end
  resources :maps, only: [:index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  validates :title, presence: true
  validates :title, length:{in:1..20}
  validates :content, presence: true
  validates :content, length:{in:1..50}
  validate :visitday_cannot_be_in_the_pastday
  validates :status, presence: true

  def visitday_cannot_be_in_the_pastday
    if visit_date.present? && visit_date < Date.today
      errors.add(:visit_date, "過去の日は入力できません。")
    end
  end


  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :picture, ImageUploader
  enum status:{緊急: 0,とても重要: 1,重要: 2,ふつう: 3, いつでもよい: 4}, _suffix: true



end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
  validates :content, presence: true
  validates :content, length:{in:1..100}

end

app/models/drink.rb
class Drink < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}
  validates :kind, presence: true
  enum kind:{ドリンク: 0,ウイスキー、ハイボール: 1,プレミアム焼酎ハイボール: 2,サワー、お茶ハイ: 3}, _suffix: true
end

app/models/food.rb
class Food < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}

end

app/models/sake.rb
class Sake < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, absence: true
  validates :kind, presence: true
  enum kind:{一列目: 0,二列目: 1,三列目: 2,四列目: 3}, _suffix: true
end

app/models/side_menu.rb
class SideMenu < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length:{in:1..20}
  validates :price, presence: true
  validates :price, numericality: {
            only_integer: true, greater_than_or_equal_to: 0}
  validates :kind, presence: true
  enum kind:{一品料理: 0,〆もの: 1}, _suffix: true
end

app/models/top.rb
class Top < ApplicationRecord
  mount_uploader :picture, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true
  validates :email, uniqueness: true

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }




  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google]
  has_many :blogs
  has_many :comments, through: :blogs


  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    puts '**********'
    puts auth.info
    puts '**********'

    unless user
      user = User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                 )
    end
    user.save
    user
  end



  def self.find_for_facebook(auth)
    user = User.find_by(email: auth.info.email)
    puts '**********'
    puts auth.info
    puts '**********'

    unless user
      user = User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                 )
    end
    user.save
    user
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/side_menus_controller.rb
class SideMenusController < ApplicationController
  before_action :set_side_menu, only: [:show, :edit, :update, :destroy]
  before_action :refuse_to_go_to, only: [:new, :edit]



  def index
    @side_menus = SideMenu.all
  end

  def new
      @side_menu = SideMenu.new
  end

  def create
    @side_menu = SideMenu.create(side_menu_params)
    if @side_menu.save
      redirect_to side_menus_path, notice:"サイドメニューを作成しました！"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @side_menu.update(side_menu_params)
      redirect_to side_menus_path, notice:"サイドメニューを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @side_menu.destroy
    redirect_to side_menus_path, notice:"サイドメニューを削除しました！"
  end

  private

  def side_menu_params
    params.require(:side_menu).permit(:name, :picture, :picture_cache, :price, :kind)
  end

  def set_side_menu
    @side_menu = SideMenu.find(params[:id])
  end

  def refuse_to_go_to
    if current_user == nil
      redirect_to tops_path, notice: '権限がありません。'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/oauth_test_helper.rb
module OauthTestHelper
end

app/helpers/sakes_helper.rb
module SakesHelper
end

app/helpers/side_menus_helper.rb
module SideMenusHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/side_menus/_form.html.erb

<%= form_with(model: @side_menu, local: true) do |form| %>
  <% if @side_menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= @side_menu.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @side_menu.errors.full_messages.each do |msg| %>
        <li><%=msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="side_menu_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="side_menu_picture">
    <%= form.label :picture%>
    <%= form.file_field :picture %>
    <% if @side_menu.picture.url %>
      <%= image_tag @side_menu.picture.url,:width => '25%', :height => '25%'  %>
    <% end %>
    <br>

  </div>
  <div class="side_menu_price">
    <%= form.label :price %>
    <%= form.number_field(:price, in: 1..99999, step: 1.0) %>
  </div>
  <div class="side_menu_kind">
    <%= form.label :kind %>
    <%= form.select :kind, SideMenu.kinds.keys.to_a, {} %>
  </div>





  <%= form.submit %>
<% end %>

<%= link_to "サイドメニュー一覧画面に戻る", side_menus_path %>

app/views/side_menus/edit.html.erb
<div class="menuediter">
<h2>一品料理を編集する</h2>
<%= render 'form' %>
</div>

app/views/side_menus/index.html.erb
<div class="side_menubody">
<div class="container">
  <div class="ordertype">
    <p1>一品料理</p1>
  </div>
  <div class="order-title" >
      <p2>京都坂ノ途中監修の無農薬オーガニック野菜など、焼き鳥の合間に一品料理も是非お楽しみください。</p2>
  </div>

  <% if current_user == nil %>
  <% elsif %>
    <button type="button" class="btn btn-danger rounded-pill">
    <%=link_to '新しく一品料理を登録する', new_side_menu_path %></button>
  <% end %>



  <br>



  <div class="row">
   <div class="col">
     <div class = "side_menukind0">
       <table height="100">
         <thead>
          <tr>
            <th height="100"><h2>[一品料理]</h2></th>
            <th height="100">お値段</th>
          </tr>
         </thead>
         <tbody>
            <% @side_menus.each do |side_menu| %>
            <% if side_menu.kind == '一品料理' %>
          <tr>
            <td><%= side_menu.name %></td>
            <td><%= side_menu.price %></td>
            <td>
            <% if side_menu.picture && side_menu.picture.url %>
                <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter-<%= side_menu.id %>">
              <%= '🐓' %>
            <% else %>
              <%= '　'%>
            <% end %>
              </button>
              <div class="modal fade" id="exampleModalCenter-<%= side_menu.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle-<%= side_menu.id %>" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <p5 class="modal-title" id="exampleModalCenterTitle-<%= side_menu.id %>"><%= side_menu.name %></p5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                          <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                      <div class="modal-body">
                        <div class="modalpicture">
                          <p><%= image_tag "#{side_menu.picture.url}",:width => '50%', :height => '50%' %></p>
                        </div>
                      </div>
                    <div class="modal-footer">
                      <h5><%= side_menu.price %>円</h5>
                    </div>
                  </div>
                </div>
              </div>
              </td>
                <% if current_user == nil %>
                <% elsif %>
                  <td>
                    <button type="button" class="btn btn-warning rounded-pill">
                    <%= link_to '編集', edit_side_menu_path(side_menu.id), data: { confirm: '本当に編集していいですか？' } %></button></td>
                  <td>
                    <button type="button" class="btn btn-secondary rounded-pill">
                    <%= link_to '削除', side_menu_path(side_menu.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></button></td>
                <% end %>
          </tr>
        　  <% end %>
        　  <% end %>
      </tbody>
    　</table>
    </div>
   </div>

   <div class="col">
     <div class = "side_menukind1">
       <table height="100">
        <thead>        　　
          <tr>
            <th height="100"><h2>[〆もの]</h2></th>
            <th height="100">お値段</th>
          </tr>
         </thead>
         <tbody>
            <% @side_menus.each do |side_menu| %>
            <% if side_menu.kind == '〆もの' %>
          <tr>
            <td><%= side_menu.name %></td>
            <td><%= side_menu.price %></td>
            <td>
            <% if side_menu.picture && side_menu.picture.url %>
                <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter-<%= side_menu.id %>">
              <%= '🐓' %>
            <% else %>
              <%= '　'%>
            <% end %>
              </button>
              <div class="modal fade" id="exampleModalCenter-<%= side_menu.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle-<%= side_menu.id %>" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered
                " role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <p5 class="modal-title" id="exampleModalCenterTitle-<%= side_menu.id %>"><%= side_menu.name %></p5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                          <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                      <div class="modal-body">
                        <div class="modalpicture">
                          <p><%= image_tag "#{side_menu.picture.url}",:width => '50%', :height => '50%' %></p>
                        </div>
                      </div>
                    <div class="modal-footer">
                      <h5><%= side_menu.price %>円</h5>
                    </div>
                  </div>
                </div>
              </div>
              </td>
                <% if current_user == nil %>
                <% elsif %>
                  <td>
                    <button type="button" class="btn btn-warning rounded-pill">
                    <%= link_to '編集', edit_side_menu_path(side_menu.id), data: { confirm: '本当に編集していいですか？' } %></button></td>
                  <td>
                    <button type="button" class="btn btn-secondary rounded-pill">
                    <%= link_to '削除', side_menu_path(side_menu.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></button></td>
                <% end %>
          </tr>
        　  <% end %>
        　  <% end %>
      　</tbody>
    　</table>
    </div>
   </div>


</div>
</div>

<br>

</div>

app/views/side_menus/new.html.erb
<div class="menuediter">
<h2>一品料理を作成する</h2>
<%= render 'form' %>
</div>

app/views/side_menus/show.html.erb
<h1>一品料理詳細画面</h1>
<p>一品料理: <%= @side_menu.name %></p>
<p>
  <strong>写真: </strong>
  <%= image_tag @side_menu.picture.url %>
</p>
<p>値段: <%= @side_menu.price %></p>

<%= link_to "一品料理一覧画面に戻る",side_menus_path %>